import { useState } from 'react';
import { FileText, Download, Calendar, ArrowUpRight, Loader2, CheckCircle, Mail, Send } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell } from 'recharts';
import { useDatabase } from '../context/DatabaseContext';
import { useAuth } from '../context/AuthContext';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import './Reports.css';

const EMAIL_API = 'http://localhost:3001';

/* ───────────── PDF helpers ───────────── */

function drawHeader(doc, title, subtitle) {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, pw, 44, 'F');
  doc.setFillColor(14, 165, 115);
  doc.rect(0, 36, pw, 8, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 22);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(subtitle, 14, 33);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
}

function drawFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(
      `Generated by EcoWaste  |  ${new Date().toLocaleString()}  |  Page ${i} of ${pageCount}`,
      pw / 2, ph - 10, { align: 'center' }
    );
  }
}

/* ─── Build a SINGLE report PDF ─── */
function buildSingleReportPDF(report) {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();

  drawHeader(doc, report.title, `Report Type: ${report.type.toUpperCase()}  |  Period: ${report.period}`);

  let y = 56;
  const totalWaste = report.totalWaste || 1;

  // Summary Box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(14, y, pw - 28, 40, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('REPORT SUMMARY', 20, y + 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  [`Total Waste: ${report.totalWaste} kg`, `Efficiency: ${report.efficiency}%`, `Collections: ${report.collections}`]
    .forEach((item, i) => doc.text(`-  ${item}`, 22, y + 20 + i * 7));

  y += 50;

  // Waste Breakdown Table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Waste Breakdown', 14, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Weight (kg)', '% of Total']],
    body: [
      ['Wet Waste', `${report.wet}`, `${((report.wet / totalWaste) * 100).toFixed(1)}%`],
      ['Dry Waste', `${report.dry}`, `${((report.dry / totalWaste) * 100).toFixed(1)}%`],
      ['Metal Waste', `${report.metal}`, `${((report.metal / totalWaste) * 100).toFixed(1)}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 16;

  // Visual Bar Chart
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Visual Breakdown', 14, y);
  y += 8;

  const categories = [
    { name: 'Wet', value: report.wet, color: [16, 185, 129] },
    { name: 'Dry', value: report.dry, color: [59, 130, 246] },
    { name: 'Metal', value: report.metal, color: [245, 158, 11] },
  ];
  const maxVal = Math.max(...categories.map(c => c.value)) || 1;
  const barMaxW = pw - 70;

  categories.forEach((cat, i) => {
    const barW = Math.max((cat.value / maxVal) * barMaxW, 4);
    doc.setFillColor(...cat.color);
    doc.roundedRect(50, y + i * 16, barW, 10, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.setFont('helvetica', 'bold');
    doc.text(cat.name, 14, y + i * 16 + 7);
    doc.setFont('helvetica', 'normal');
    doc.text(`${cat.value} kg`, 52 + barW, y + i * 16 + 7);
  });

  drawFooter(doc);
  return doc;
}

/* ─── Build a COMPREHENSIVE summary PDF ─── */
function buildSummaryReportPDF(reportList, filterLabel) {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();

  drawHeader(doc, 'EcoWaste — Comprehensive Report', `Filter: ${filterLabel}  |  Generated: ${new Date().toLocaleDateString()}`);

  let y = 56;

  const totalWaste = reportList.reduce((s, r) => s + (r.totalWaste || 0), 0);
  const avgEfficiency = reportList.length ? (reportList.reduce((s, r) => s + (r.efficiency || 0), 0) / reportList.length).toFixed(1) : 0;
  const totalCollections = reportList.reduce((s, r) => s + (r.collections || 0), 0);
  const totalWet = reportList.reduce((s, r) => s + (r.wet || 0), 0);
  const totalDry = reportList.reduce((s, r) => s + (r.dry || 0), 0);
  const totalMetal = reportList.reduce((s, r) => s + (r.metal || 0), 0);

  // Overview Box
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(14, y, pw - 28, 46, 3, 3, 'F');
  doc.setDrawColor(16, 185, 129);
  doc.roundedRect(14, y, pw - 28, 46, 3, 3, 'S');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 100, 80);
  doc.text('OVERVIEW', 20, y + 10);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  [`Reports: ${reportList.length}`, `Total Waste: ${totalWaste} kg`, `Avg Efficiency: ${avgEfficiency}%`, `Total Collections: ${totalCollections}`]
    .forEach((line, i) => doc.text(`-  ${line}`, 22, y + 19 + i * 7));

  y += 56;

  // All Reports Table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('All Reports', 14, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [['Title', 'Type', 'Period', 'Total (kg)', 'Wet', 'Dry', 'Metal', 'Eff %', 'Collections']],
    body: reportList.map(r => [r.title, r.type, r.period, r.totalWaste, r.wet, r.dry, r.metal, `${r.efficiency}%`, r.collections]),
    theme: 'striped',
    headStyles: { fillColor: [16, 185, 129], textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5 },
    margin: { left: 14, right: 14 },
    styles: { cellPadding: 3 },
  });

  y = doc.lastAutoTable.finalY + 16;

  // Waste Composition
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Waste Composition Summary', 14, y);
  y += 4;

  const grandTotal = totalWaste || 1;
  autoTable(doc, {
    startY: y,
    head: [['Category', 'Total Weight (kg)', '% of Total']],
    body: [
      ['Wet Waste', `${totalWet}`, `${((totalWet / grandTotal) * 100).toFixed(1)}%`],
      ['Dry Waste', `${totalDry}`, `${((totalDry / grandTotal) * 100).toFixed(1)}%`],
      ['Metal Waste', `${totalMetal}`, `${((totalMetal / grandTotal) * 100).toFixed(1)}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [239, 246, 255] },
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 16;

  // Visual bars
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Waste Composition Chart', 14, y);
  y += 10;

  const catBars = [
    { name: 'Wet Waste', value: totalWet, color: [16, 185, 129] },
    { name: 'Dry Waste', value: totalDry, color: [59, 130, 246] },
    { name: 'Metal Waste', value: totalMetal, color: [245, 158, 11] },
  ];
  const maxBarVal = Math.max(...catBars.map(c => c.value)) || 1;
  const maxBarW = pw - 80;

  catBars.forEach((cat, i) => {
    const barW = Math.max((cat.value / maxBarVal) * maxBarW, 4);
    doc.setFillColor(...cat.color);
    doc.roundedRect(56, y + i * 18, barW, 12, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.setFont('helvetica', 'bold');
    doc.text(cat.name, 14, y + i * 18 + 8);
    doc.setFont('helvetica', 'normal');
    doc.text(`${cat.value} kg`, 58 + barW, y + i * 18 + 8);
  });

  drawFooter(doc);
  return doc;
}

/* ───────────── Custom Tooltip ───────────── */

const CustomTooltip = ({ active, payload, label }) => {
  if (!active || !payload) return null;
  return (
    <div className="chart-tooltip">
      <p className="tooltip-label">{label}</p>
      {payload.map((entry, i) => (
        <div key={i} className="tooltip-row">
          <span className="tooltip-dot" style={{ background: entry.color }} />
          <span>{entry.name}: {entry.value} kg</span>
        </div>
      ))}
    </div>
  );
};

/* ───────────── Reports Page ───────────── */

export default function Reports() {
  const { reports, loading } = useDatabase();
  const { currentUser } = useAuth();
  const [typeFilter, setTypeFilter] = useState('all');
  const [exportingId, setExportingId] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [successId, setSuccessId] = useState(null);
  const [emailingId, setEmailingId] = useState(null);     // per-card email status
  const [emailSentId, setEmailSentId] = useState(null);   // per-card email success
  const [emailingAll, setEmailingAll] = useState(false);   // generate+email all
  const [emailAllSent, setEmailAllSent] = useState(false);

  const userEmail = currentUser?.email;

  if (loading || !reports) {
    return (
      <div className="page">
        <div className="loading-state">
          <div className="loading-spinner" />
          <p>Connecting to Firebase...</p>
        </div>
      </div>
    );
  }

  const reportList = Array.isArray(reports) ? reports : Object.values(reports);
  const filtered = typeFilter === 'all' ? reportList : reportList.filter(r => r.type === typeFilter);
  const filterLabel = typeFilter.charAt(0).toUpperCase() + typeFilter.slice(1);

  /* ── Export + Download a single report PDF ── */
  const handleExportPDF = (report) => {
    try {
      setExportingId(report.id);
      const doc = buildSingleReportPDF(report);
      doc.save(`EcoWaste_${report.type}_report_${report.period.replace(/\s+/g, '_')}.pdf`);
      setSuccessId(report.id);
      setTimeout(() => setSuccessId(null), 2000);
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('Failed to export PDF.\n\n' + err.message);
    } finally {
      setExportingId(null);
    }
  };

  /* ── Email a single report PDF to the user ── */
  const handleEmailReport = async (report) => {
    if (!userEmail) {
      alert('You must be logged in to email reports.');
      return;
    }
    try {
      setEmailingId(report.id);
      const doc = buildSingleReportPDF(report);
      const pdfBase64 = doc.output('datauristring').split(',')[1]; // strip data:... prefix
      const fileName = `EcoWaste_${report.type}_report_${report.period.replace(/\s+/g, '_')}.pdf`;

      const res = await fetch(`${EMAIL_API}/send-report`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          recipientEmail: userEmail,
          reportTitle: report.title,
          reportPeriod: report.period,
          reportType: report.type,
          pdfBase64,
          fileName,
        }),
      });

      const data = await res.json();
      if (res.ok && data.success) {
        setEmailSentId(report.id);
        setTimeout(() => setEmailSentId(null), 3000);
      } else {
        throw new Error(data.error || 'Failed to send');
      }
    } catch (err) {
      console.error('Email report failed:', err);
      alert('Failed to email report. Make sure the email server is running.\n\n' + err.message);
    } finally {
      setEmailingId(null);
    }
  };

  /* ── Generate + Download comprehensive PDF ── */
  const handleGenerateReport = () => {
    if (!filtered.length) {
      alert('No reports available to generate a PDF from.');
      return;
    }
    try {
      setGenerating(true);
      const doc = buildSummaryReportPDF(filtered, filterLabel);
      doc.save(`EcoWaste_Summary_${filterLabel}_${new Date().toISOString().slice(0, 10)}.pdf`);
    } catch (err) {
      console.error('Report generation failed:', err);
      alert('Failed to generate report.\n\n' + err.message);
    } finally {
      setGenerating(false);
    }
  };

  /* ── Generate + Email comprehensive PDF ── */
  const handleEmailAllReports = async () => {
    if (!userEmail) {
      alert('You must be logged in to email reports.');
      return;
    }
    if (!filtered.length) {
      alert('No reports available to email.');
      return;
    }
    try {
      setEmailingAll(true);
      const doc = buildSummaryReportPDF(filtered, filterLabel);
      const pdfBase64 = doc.output('datauristring').split(',')[1];
      const fileName = `EcoWaste_Summary_${filterLabel}_${new Date().toISOString().slice(0, 10)}.pdf`;

      const res = await fetch(`${EMAIL_API}/send-report`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          recipientEmail: userEmail,
          reportTitle: `EcoWaste Comprehensive Report (${filterLabel})`,
          reportPeriod: `${filtered.length} reports`,
          reportType: filterLabel,
          pdfBase64,
          fileName,
        }),
      });

      const data = await res.json();
      if (res.ok && data.success) {
        setEmailAllSent(true);
        setTimeout(() => setEmailAllSent(false), 3000);
      } else {
        throw new Error(data.error || 'Failed to send');
      }
    } catch (err) {
      console.error('Email all reports failed:', err);
      alert('Failed to email report. Make sure the email server is running.\n\n' + err.message);
    } finally {
      setEmailingAll(false);
    }
  };

  return (
    <div className="page">
      <div className="page-header animate-fade-in-up">
        <h1>Reports</h1>
        <p>Generate and view waste management reports</p>
      </div>

      {/* Type Filter + Action Buttons */}
      <div className="reports-controls animate-fade-in-up">
        <div className="filter-group">
          {['all', 'daily', 'weekly', 'monthly'].map(t => (
            <button
              key={t}
              className={`filter-btn ${typeFilter === t ? 'active' : ''}`}
              onClick={() => setTypeFilter(t)}
            >
              {t.charAt(0).toUpperCase() + t.slice(1)}
            </button>
          ))}
        </div>
        <div className="reports-header-actions">
          <button
            className={`btn ${emailAllSent ? 'btn-email-sent' : 'btn-email-report'}`}
            onClick={handleEmailAllReports}
            disabled={emailingAll}
          >
            {emailingAll ? (
              <><Loader2 size={15} className="spin-icon" /> Emailing…</>
            ) : emailAllSent ? (
              <><CheckCircle size={15} /> Sent to {userEmail}!</>
            ) : (
              <><Send size={15} /> Email All Reports</>
            )}
          </button>
          <button
            className="btn btn-primary"
            onClick={handleGenerateReport}
            disabled={generating}
          >
            {generating ? (
              <><Loader2 size={16} className="spin-icon" /> Generating…</>
            ) : (
              <><FileText size={16} /> Generate Report</>
            )}
          </button>
        </div>
      </div>

      {/* Report Cards */}
      <div className="reports-list stagger-children">
        {filtered.map(report => (
          <div key={report.id} className="report-card glass-card">
            <div className="report-card-header">
              <div className="report-icon-wrapper">
                <FileText size={20} />
              </div>
              <div className="report-meta">
                <h3 className="report-title">{report.title}</h3>
                <div className="report-period">
                  <Calendar size={13} />
                  <span>{report.period}</span>
                </div>
              </div>
              <span className={`badge badge-${report.type === 'daily' ? 'info' : report.type === 'weekly' ? 'warning' : 'success'}`}>
                {report.type}
              </span>
            </div>

            {/* Mini Chart */}
            <div className="report-chart">
              <ResponsiveContainer width="100%" height={120}>
                <BarChart data={[
                  { name: 'Wet', value: report.wet, fill: '#10b981' },
                  { name: 'Dry', value: report.dry, fill: '#3b82f6' },
                  { name: 'Metal', value: report.metal, fill: '#f59e0b' },
                ]} margin={{ top: 5, right: 5, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--border-secondary)" />
                  <XAxis dataKey="name" tick={{ fill: 'var(--text-tertiary)', fontSize: 11 }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: 'var(--text-tertiary)', fontSize: 11 }} axisLine={false} tickLine={false} />
                  <Tooltip content={<CustomTooltip />} />
                  <Bar dataKey="value" name="Weight" radius={[4, 4, 0, 0]}>
                    {[
                      { name: 'Wet', fill: '#10b981' },
                      { name: 'Dry', fill: '#3b82f6' },
                      { name: 'Metal', fill: '#f59e0b' },
                    ].map((entry, i) => (
                      <Cell key={i} fill={entry.fill} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Stats Grid */}
            <div className="report-stats-grid">
              <div className="report-stat">
                <span className="report-stat-value">{report.totalWaste} kg</span>
                <span className="report-stat-label">Total Waste</span>
              </div>
              <div className="report-stat">
                <span className="report-stat-value">{report.efficiency}%</span>
                <span className="report-stat-label">Efficiency</span>
              </div>
              <div className="report-stat">
                <span className="report-stat-value">{report.collections}</span>
                <span className="report-stat-label">Collections</span>
              </div>
            </div>

            {/* Actions */}
            <div className="report-actions">
              <button
                className={`btn btn-sm ${successId === report.id ? 'btn-success-flash' : 'btn-outline'}`}
                onClick={() => handleExportPDF(report)}
                disabled={exportingId === report.id}
              >
                {exportingId === report.id ? (
                  <><Loader2 size={14} className="spin-icon" /> Exporting…</>
                ) : successId === report.id ? (
                  <><CheckCircle size={14} /> Downloaded!</>
                ) : (
                  <><Download size={14} /> Export PDF</>
                )}
              </button>
              <button
                className={`btn btn-sm ${emailSentId === report.id ? 'btn-email-sent-sm' : 'btn-email-sm'}`}
                onClick={() => handleEmailReport(report)}
                disabled={emailingId === report.id}
              >
                {emailingId === report.id ? (
                  <><Loader2 size={14} className="spin-icon" /> Sending…</>
                ) : emailSentId === report.id ? (
                  <><CheckCircle size={14} /> Emailed!</>
                ) : (
                  <><Mail size={14} /> Email</>
                )}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
